[connections.mysql]
dialect = "mysql"
host = "my-mysql"
port = 3306
database = "demo_db"
username = "user"
password = "user_pass"

[connections.mysql2]
dialect = "mysql"
host = "my-mysql"
port = 3306
database = "demo_db2"
username = "user"
password = "user_pass"
